package com.sireph.technics.utils.statics;

public enum Flag {
    ADDED_TRAUMA,
    UPDATED_SYMPTOM,
    UPDATED_CIRCULATION,
    UPDATED_PROTOCOL,
    UPDATED_RCP,
    UPDATED_SCALE,
    UPDATED_VENTILATION,
    ADDED_EVALUATION,
    ADDED_PHARMACY,
    ADDED_STATE,
    UPDATED_TRANSPORT,
    UPDATED_VICTIM,
    ADDED_VICTIM,
    UPDATED_OCCURRENCE,
    FOUND
}
